import { useState } from "react";
import { FileCheck2, Download, CheckCircle2, AlertCircle, XCircle, Clock, Filter, ExternalLink } from "lucide-react";
import { Card, CardHeader, PageHeader, Button } from "../components/ui/primitives";
import { useEvidence } from "../lib/queries";
import type { Evidence as EvidenceType } from "../lib/store";

const frameworks = ["SOC 2", "ISO 27001", "HIPAA", "PCI-DSS", "SEBI CSCRF"] as const;

const statusConfig = {
  SATISFIED: { label: "Satisfied", icon: CheckCircle2, color: "text-s-success", bg: "bg-s-success/10 border-s-success/30" },
  PARTIAL: { label: "Partial", icon: AlertCircle, color: "text-s-warning", bg: "bg-s-warning/10 border-s-warning/30" },
  MISSING: { label: "Missing", icon: XCircle, color: "text-s-critical", bg: "bg-s-critical/10 border-s-critical/30" },
};

export function Evidence() {
  const { data: evidence = [] } = useEvidence();
  const [framework, setFramework] = useState<string>("SOC 2");

  const filtered = evidence.filter((e) => e.framework === framework);
  const allForFramework = filtered;

  const stats = {
    satisfied: allForFramework.filter((e) => e.status === "SATISFIED").length,
    partial: allForFramework.filter((e) => e.status === "PARTIAL").length,
    missing: allForFramework.filter((e) => e.status === "MISSING").length,
    total: allForFramework.length,
  };

  const coveragePercent = stats.total > 0
    ? Math.round(((stats.satisfied + stats.partial * 0.5) / stats.total) * 100)
    : 0;

  return (
    <div>
      <PageHeader
        title="Evidence Explorer"
        description="Compliance evidence auto-generated by agents, mapped to control frameworks"
        action={
          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" icon={<Filter size={13} />}>Filters</Button>
            <Button variant="primary" size="sm" icon={<Download size={13} />}>Export Package</Button>
          </div>
        }
      />

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-5">
        <Card className="p-4 overflow-hidden">
          <div className="label-mono mb-2">Coverage</div>
          <div className="flex items-baseline gap-2">
            <span className="font-mono text-s-primary text-[28px] font-medium tabular-nums">{coveragePercent}%</span>
            <span className="text-s-muted text-[11px]">of controls</span>
          </div>
          <div className="w-full h-2 bg-s-subtle rounded-full overflow-hidden mt-2">
            <div className="h-full bg-s-success rounded-full" style={{ width: `${coveragePercent}%` }} />
          </div>
        </Card>
        <Card className="p-4 overflow-hidden">
          <div className="flex items-center gap-1.5 mb-2">
            <CheckCircle2 size={12} className="text-s-success" />
            <span className="label-mono">Satisfied</span>
          </div>
          <div className="font-mono text-s-success text-2xl font-medium tabular-nums">{stats.satisfied}</div>
        </Card>
        <Card className="p-4 overflow-hidden">
          <div className="flex items-center gap-1.5 mb-2">
            <AlertCircle size={12} className="text-s-warning" />
            <span className="label-mono">Partial</span>
          </div>
          <div className="font-mono text-s-warning text-2xl font-medium tabular-nums">{stats.partial}</div>
        </Card>
        <Card className="p-4 overflow-hidden">
          <div className="flex items-center gap-1.5 mb-2">
            <XCircle size={12} className="text-s-critical" />
            <span className="label-mono">Missing</span>
          </div>
          <div className="font-mono text-s-critical text-2xl font-medium tabular-nums">{stats.missing}</div>
        </Card>
      </div>

      <Card className="mb-5 overflow-hidden">
        <div className="px-5 py-4 border-b border-s-border">
          <div className="label-mono mb-2">Framework</div>
          <div className="flex flex-wrap gap-1.5">
            {frameworks.map((f) => {
              const count = evidence.filter((e) => e.framework === f).length;
              return (
                <button
                  key={f}
                  onClick={() => setFramework(f)}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-md border text-xs font-medium transition-colors ${
                    framework === f
                      ? "bg-s-brand/10 text-s-brand border-s-brand/40"
                      : "border-s-border text-s-secondary hover:border-s-border-strong hover:text-s-primary"
                  }`}
                >
                  {f}
                  {count > 0 && (
                    <span className="font-mono opacity-70 text-[10px]">{count}</span>
                  )}
                </button>
              );
            })}
          </div>
        </div>
      </Card>

      <Card className="overflow-hidden">
        <CardHeader
          title={`${framework} Evidence`}
          subtitle={`${stats.total} control${stats.total !== 1 ? "s" : ""} mapped`}
        />
        {allForFramework.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 px-6 text-center">
            <div className="w-10 h-10 rounded-md bg-s-subtle border border-s-border flex items-center justify-center text-s-muted mb-4">
              <FileCheck2 size={18} />
            </div>
            <div className="text-s-primary text-sm font-medium mb-1">No evidence for {framework}</div>
            <div className="text-s-secondary max-w-sm text-[12.5px] leading-relaxed">
              As workflows execute, agents will produce evidence mapped to {framework} controls.
            </div>
          </div>
        ) : (
          <div className="divide-y divide-s-border">
            {allForFramework.map((ev) => (
              <EvidenceRow key={ev.id} evidence={ev} />
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}

function EvidenceRow({ evidence }: { evidence: EvidenceType }) {
  const cfg = statusConfig[evidence.status];
  const Icon = cfg.icon;

  return (
    <div className="px-5 py-4 hover:bg-s-hover transition-colors">
      <div className="flex items-start gap-3">
        <div className={`mt-0.5 shrink-0 ${cfg.color}`}>
          <Icon size={16} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="font-mono text-s-brand text-[11px] font-medium">{evidence.controlId}</span>
            <span className={`inline-flex items-center px-1.5 py-0.5 rounded border text-[9.5px] font-medium ${cfg.bg} ${cfg.color}`}>
              {cfg.label}
            </span>
          </div>
          <div className="text-s-primary text-[12.5px] leading-relaxed">
            {evidence.description}
          </div>
          <div className="flex items-center gap-3 mt-2 flex-wrap">
            {evidence.agentId && (
              <span className="text-s-muted font-mono text-[10px]">{evidence.agentId}</span>
            )}
            {evidence.workflowId && (
              <span className="flex items-center gap-1 text-s-muted text-[10px]">
                <ExternalLink size={9} /> {evidence.workflowId}
              </span>
            )}
            <span className="flex items-center gap-1 text-s-muted text-[10px]">
              <Clock size={9} /> {formatAge(Date.now() - evidence.generatedAt)}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

function formatAge(ms: number): string {
  const hours = Math.floor(ms / 3600000);
  if (hours < 1) return `${Math.floor(ms / 60000)}m ago`;
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}
