import { nanoid } from 'nanoid';
import type { AgentProjectSdkManifest } from './types.js';

export function sdkManifest(apiBase = '/api/v1'): AgentProjectSdkManifest {
  return {
    id: `sdk_${nanoid(10)}`,
    generatedAt: new Date().toISOString(),
    apiBase,
    endpoints: [
      { method: 'GET', path: '/agent-projects/projects', purpose: 'List scoped agent projects.' },
      { method: 'POST', path: '/agent-projects/projects', purpose: 'Create governed project scopes.' },
      { method: 'POST', path: '/agent-projects/runs', purpose: 'Plan slash-command agent runs.' },
      { method: 'POST', path: '/agent-projects/runs/:id/workspace-plan', purpose: 'Prepare worktree and command plan.' },
      { method: 'GET', path: '/agent-projects/delivery-jobs', purpose: 'List durable delivery pipeline jobs.' },
      { method: 'POST', path: '/agent-projects/delivery-jobs', purpose: 'Queue a stage-gated delivery job.' },
      { method: 'POST', path: '/agent-projects/delivery-jobs/:id/run', purpose: 'Run a queued delivery job through workspace, execution, proof, and handoff stages.' },
      { method: 'GET', path: '/agent-projects/delivery-jobs/:id/events', purpose: 'Tail delivery job events with progress and lease state.' },
      { method: 'POST', path: '/agent-projects/delivery-jobs/:id/heartbeat', purpose: 'Renew delivery job heartbeat and progress evidence.' },
      { method: 'POST', path: '/agent-projects/delivery-jobs/:id/cancel', purpose: 'Cancel a delivery job before further mutation.' },
      { method: 'POST', path: '/agent-projects/delivery-jobs/:id/retry', purpose: 'Reset a blocked or failed delivery job for retry.' },
      { method: 'POST', path: '/agent-projects/projects/:id/runtime-profile', purpose: 'Generate project-local agent, hook, slash-command, and MCP files.' },
      { method: 'POST', path: '/agent-projects/hooks/run', purpose: 'Evaluate project hooks with artifacted policy evidence.' },
      { method: 'POST', path: '/agent-projects/runs/:id/pr-package', purpose: 'Create review-ready PR body and delivery evidence package.' },
      { method: 'GET', path: '/agent-projects/execution-fabric/plans', purpose: 'List provider execution, PR, deploy, and cost-gated fabric plans.' },
      { method: 'POST', path: '/agent-projects/execution-fabric/plans', purpose: 'Create a provider adapter manifest with budget, secret, rollout, and rollback gates.' },
      { method: 'GET', path: '/agent-projects/execution-fabric/jobs', purpose: 'List execution fabric jobs and provider handoff evidence.' },
      { method: 'POST', path: '/agent-projects/execution-fabric/jobs', purpose: 'Run a dry-run or approved live execution fabric job.' },
      { method: 'GET', path: '/agent-projects/execution-fabric/jobs/:id/events', purpose: 'Tail execution fabric events with progress and lease state.' },
      { method: 'POST', path: '/agent-projects/execution-fabric/jobs/:id/heartbeat', purpose: 'Renew execution fabric heartbeat and progress evidence.' },
      { method: 'POST', path: '/agent-projects/executions', purpose: 'Launch an execution envelope.' },
      { method: 'POST', path: '/agent-projects/executions/:id/commands', purpose: 'Run approved workspace command evidence.' },
      { method: 'POST', path: '/agent-projects/executions/:id/browser-evidence', purpose: 'Attach Browser QA evidence.' },
      { method: 'POST', path: '/agent-projects/executions/:id/delivery-pack', purpose: 'Package release/customer evidence.' },
      { method: 'POST', path: '/agent-projects/schedules/run-due', purpose: 'Dispatch due scheduled work.' },
    ],
    cliCommands: [
      'npm run axon -- projects',
      'npm run axon -- plan --project apj_x --prompt "/goal ..."',
      'npm run axon -- workspace --run apr_x',
      'npm run axon -- launch --run apr_x --autonomy supervised',
      'npm run axon -- queue-job --run apr_x',
      'npm run axon -- run-job --job job_x',
      'npm run axon -- job-events --job job_x',
      'npm run axon -- job-heartbeat --job job_x --owner WebOperator --progress 55',
      'npm run axon -- runtime-profile --project apj_x --run apr_x',
      'npm run axon -- run-hook --project apj_x --event loop-stop --approved',
      'npm run axon -- pr-package --run apr_x --execution apx_x',
      'npm run axon -- fabric-plan --run apr_x --provider github-actions --deploy vercel --env staging',
      'npm run axon -- fabric-run --plan xfp_x --approved --live',
      'npm run axon -- fabric-events --job xfj_x',
      'npm run axon -- fabric-heartbeat --job xfj_x --owner ReleaseOperator --progress 70',
      'npm run axon -- run-command --execution apx_x --index 0 --approved',
      'npm run axon -- browser-evidence --execution apx_x --url https://preview.customer-domain.com',
    ],
    sdkTargets: [
      { language: 'typescript', packageName: '@axon/agent-projects-client', status: 'ready-contract' },
      { language: 'python', packageName: 'axon-agent-projects', status: 'ready-contract' },
      { language: 'go', packageName: 'github.com/axon/agentprojects', status: 'planned' },
    ],
    mcpTools: [
      { name: 'agent_projects.list', route: 'GET /agent-projects/projects', approvalRequired: false },
      { name: 'agent_projects.plan', route: 'POST /agent-projects/runs', approvalRequired: false },
      { name: 'agent_projects.queue_job', route: 'POST /agent-projects/delivery-jobs', approvalRequired: false },
      { name: 'agent_projects.run_job', route: 'POST /agent-projects/delivery-jobs/:id/run', approvalRequired: true },
      { name: 'agent_projects.tail_job_events', route: 'GET /agent-projects/delivery-jobs/:id/events', approvalRequired: false },
      { name: 'agent_projects.heartbeat_job', route: 'POST /agent-projects/delivery-jobs/:id/heartbeat', approvalRequired: false },
      { name: 'agent_projects.runtime_profile', route: 'POST /agent-projects/projects/:id/runtime-profile', approvalRequired: false },
      { name: 'agent_projects.run_hook', route: 'POST /agent-projects/hooks/run', approvalRequired: true },
      { name: 'agent_projects.pr_package', route: 'POST /agent-projects/runs/:id/pr-package', approvalRequired: false },
      { name: 'agent_projects.fabric_plan', route: 'POST /agent-projects/execution-fabric/plans', approvalRequired: false },
      { name: 'agent_projects.fabric_run', route: 'POST /agent-projects/execution-fabric/jobs', approvalRequired: true },
      { name: 'agent_projects.tail_fabric_events', route: 'GET /agent-projects/execution-fabric/jobs/:id/events', approvalRequired: false },
      { name: 'agent_projects.heartbeat_fabric_job', route: 'POST /agent-projects/execution-fabric/jobs/:id/heartbeat', approvalRequired: false },
      { name: 'agent_projects.launch', route: 'POST /agent-projects/executions', approvalRequired: true },
      { name: 'agent_projects.run_command', route: 'POST /agent-projects/executions/:id/commands', approvalRequired: true },
      { name: 'agent_projects.delivery_pack', route: 'POST /agent-projects/executions/:id/delivery-pack', approvalRequired: false },
    ],
  };
}
