export const queryKeys = {
  workflows: ['workflows'] as const,
  workflow: (id: string) => ['workflow', id] as const,
  agents: ['agents'] as const,
  agent: (id: string) => ['agent', id] as const,
  agentRegistry: ['agent-registry'] as const,
  agentPipeline: ['agent-pipeline'] as const,
  approvals: ['approvals'] as const,
  approval: (id: string) => ['approval', id] as const,
  policies: ['policies'] as const,
  policy: (id: string) => ['policy', id] as const,
  memory: (query: string) => ['memory', query] as const,
  memoryAll: ['memory-all'] as const,
  audit: ['audit'] as const,
  cost: ['cost'] as const,
  incidents: ['incidents'] as const,
  incident: (id: string) => ['incident', id] as const,
  evidence: ['evidence'] as const,
  alerts: ['alerts'] as const,
  executive: ['executive'] as const,
  dag: (workflowId: string) => ['dag', workflowId] as const,
  orchestratorStatus: ['orchestrator-status'] as const,
  orchestratorAgents: ['orchestrator-agents'] as const,
  models: ['models'] as const,
  modelCatalog: ['model-catalog'] as const,
  modelRuntimeStatus: ['model-runtime-status'] as const,
  platformHealth: ['platform-health'] as const,
  integrations: ['integrations'] as const,
  modelEvaluations: ['model-evaluations'] as const,
  modelProviderConfig: ['model-provider-config'] as const,
  workspaceSettings: ['workspace-settings'] as const,
  skills: ['skills'] as const,
  toolsRegistry: ['tools-registry'] as const,
  toolsPipeline: ['tools-pipeline'] as const,
  toolsStats: ['tools-stats'] as const,
  productCatalog: ['product-catalog'] as const,
  productBlueprints: ['product-blueprints'] as const,
  productBlueprint: (id: string) => ['product-blueprint', id] as const,
  codeStatus: (workspaceId: string) => ['code-status', workspaceId] as const,
  codeSearch: (workspaceId: string, query: string) => ['code-search', workspaceId, query] as const,
  codeSymbols: (workspaceId: string, filePath: string) => ['code-symbols', workspaceId, filePath] as const,
  codeAnalysis: (workspaceId: string, filePath: string) => ['code-analysis', workspaceId, filePath] as const,
  codePatterns: (workspaceId: string) => ['code-patterns', workspaceId] as const,
  databasePolicies: ['database-policies'] as const,
  enterpriseCapabilities: ['enterprise-capabilities'] as const,
  securityScan: ['security-scan'] as const,
  checkpoints: ['checkpoints'] as const,
  checkpoint: (id: string) => ['checkpoint', id] as const,
  serviceDeskTickets: ['service-desk-tickets'] as const,
  managedServiceCatalog: ['managed-service-catalog'] as const,
  managedServiceAccounts: ['managed-service-accounts'] as const,
  managedServiceAccount: (id: string) => ['managed-service-account', id] as const,
  skillAcademyRoles: ['skill-academy-roles'] as const,
  skillAcademySources: ['skill-academy-sources'] as const,
  skillAcademyPlans: ['skill-academy-plans'] as const,
  autonomousWorkforcePlanes: ['autonomous-workforce-planes'] as const,
  companyOsMissions: ['company-os-missions'] as const,
  deliveryBrainDossiers: ['delivery-brain-dossiers'] as const,
  structureGuardianScan: ['structure-guardian-scan'] as const,
  customerDeliveryAccounts: ['customer-delivery-accounts'] as const,
  customerDeliveryAccount: (id: string) => ['customer-delivery-account', id] as const,
  apiForgeReports: ['api-forge-reports'] as const,
  apiForgeReport: (id: string) => ['api-forge-report', id] as const,
  browserQaReports: ['browser-qa-reports'] as const,
  browserQaReport: (id: string) => ['browser-qa-report', id] as const,
  releaseCommandMissions: ['release-command-missions'] as const,
  releaseCommandMission: (id: string) => ['release-command-mission', id] as const,
  missionControlRuns: ['mission-control-runs'] as const,
  missionControlRun: (id: string) => ['mission-control-run', id] as const,
  marketRadarReports: ['market-radar-reports'] as const,
  marketRadarReport: (id: string) => ['market-radar-report', id] as const,
  modelFinOpsReports: ['model-finops-reports'] as const,
  modelFinOpsReport: (id: string) => ['model-finops-report', id] as const,
  agenticMeshBlueprints: ['agentic-mesh-blueprints'] as const,
  agenticMeshBlueprint: (id: string) => ['agentic-mesh-blueprint', id] as const,
  agentProjects: ['agent-projects'] as const,
  agentProjectRuns: ['agent-project-runs'] as const,
  agentProjectSchedules: ['agent-project-schedules'] as const,
  agentProjectCapabilityRoadmap: ['agent-project-capability-roadmap'] as const,
  agentProjectWorkspacePlans: ['agent-project-workspace-plans'] as const,
  agentProjectExecutions: ['agent-project-executions'] as const,
  agentProjectDeliveryJobs: ['agent-project-delivery-jobs'] as const,
  agentProjectDeliveryJobEvents: (id: string) => ['agent-project-delivery-job-events', id] as const,
  agentProjectExecutionFabricPlans: ['agent-project-execution-fabric-plans'] as const,
  agentProjectExecutionFabricJobs: ['agent-project-execution-fabric-jobs'] as const,
  agentProjectExecutionFabricJobEvents: (id: string) => ['agent-project-execution-fabric-job-events', id] as const,
  agentProjectTemplates: ['agent-project-templates'] as const,
  agentProjectWorkerStatus: ['agent-project-worker-status'] as const,
  agentProjectSdkManifest: ['agent-project-sdk-manifest'] as const,
  productionReadinessReports: ['production-readiness-reports'] as const,
  productionReadinessActivations: ['production-readiness-activations'] as const,
  trustLedgerRecords: ['trust-ledger-records'] as const,
  trustLedgerExport: ['trust-ledger-export'] as const,
};
